:Author: abcodez
:Build Date: 2019/06/13 
:Revision: No revision as of yet

= Project: Flex Arm

This project was created in 2019 as a final grade 11 computer engineering project.
By going over various yotube videos concerning servo motors, flex sensors, etc. I was able to create my very own flex sensor controlled mechatronic arm.
With a budget of just over $100, the mechatronic was controlled by a glove with flex sensors that in turn rotated servo motors.

=== Folder structure

....
 FlexArm_2019                => Arduino sketch folder
  ├── FlexArm_2019.ino       => main Arduino file
  ├── sketch.json            => sketch file
  └── ReadMe.adoc            => this file
....


=== BOM

|===
| Part | Description | Quantity
| ELEGOO UNO | Project starter kit that includes basic materials for the project such as jumper cables, breadboard, & arduino board   |  1
| SG90 MICRO 9G | Servos used to pull on strings to move hand    |  1
| Aluminum Tape | Tape needed to create flex sensors  |  1
| Clips | Cotter pin 3/32X1 steel     | 40
| Zip Ties | 10k Resistor   |  5
| Styrofoam | Foam block to mold into hand   |  2
| Thin Wood Plank | WOOD STRIP 1/8 X 12 X 24IN CRAFT PLYWOOD   | 2
| Thin Wood Rod | WOOD STRIP 1/8 X 1/8 X 24IN BASSWOOD   |  1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
