:Author: abcodez
:Build Date: 2019/06/13 
:Revision: No revision as of yet

= Project: Flex Arm

This project was created in 2019 as a final grade 11 computer engineering project.
By going over various yotube videos concerning servo motors, flex sensors, etc. I was able to create my very own flex sensor controlled mechatronic arm.
With a budget of just over $100, the mechatronic was controlled by a glove with flex sensors that in turn rotated servo motors.

=== Folder structure

....
 FlexArm_2019                => Arduino sketch folder
  ├── FlexArm_2019.ino       => main Arduino file
  ├── sketch.json            => sketch file
  └── ReadMe.adoc            => this file
....


=== BOM

|===
| Part | Description | Quantity
| ELEGOO UNO | Project starter kit that includes basic materials for the project such as jumper cables, breadboard, & arduino board   |  1
| SG90 MICRO 9G | Servos used to pull on strings to move hand    |  1
| Aluminum Tape | Tape needed to create flex sensors  |  1
| Clips | Cotter pin 3/32X1 steel     | 40
| Zip Ties | 10k Resistor   |  5
| Styrofoam | Foam block to mold into hand   |  2
| Thin Wood Plank | WOOD STRIP 1/8 X 12 X 24IN CRAFT PLYWOOD   | 2
| Thin Wood Rod | WOOD STRIP 1/8 X 1/8 X 24IN BASSWOOD   |  1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]

=== References

(n.d.). Retrieved from https://circuitdigest.com/microcontroller-projects/servo-motor-control-by-flex-sensor-using-arduino
Arduino, M. (2017, January 02). Make a Flex Sensor for Robotic Hand and Arduino | DIY. Retrieved from https://www.youtube.com/watch?v=b7zT94WV-Ek
Codebender_cc, & Instructables. (2017, October 06). How to Use a Flex Sensor - Arduino Tutorial. Retrieved from https://www.instructables.com/id/How-to-use-a-Flex-Sensor-Arduino-Tutorial/
Hack Attack Tutorial: Controlling a Servo using a Flex Sensor » Circuit-Help. (2017, February 15). Retrieved from https://circuit-help.com.ph/tutorial-flexing-servo/
Hack Attack Tutorial: Controlling a Servo using a Flex Sensor » Circuit-Help. (2017, February 15). Retrieved from https://circuit-help.com.ph/tutorial-flexing-servo/
Official, U. V. (2017, January 20). How to interface flex sensor and servo motor with arduino. Retrieved from https://www.youtube.com/watch?v=MNiN3ye9hvY
Robojax. (2018, May 22). Control Servo motor with push button with Arduino. Retrieved from https://www.youtube.com/watch?v=7woqNH_qby4

